services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    ports:
      - 9000:8080
    environment:
      - SECURITY_ENABLELOGIN=false
      - SYSTEM_DEFAULTLOCALE=zh-CN
    restart: unless-stopped